#!/usr/bin/env bash

dir=$(pwd)
mkdir /tmp/dev-env
cd /tmp/dev-env

sudo apt install libxcb1-dev libxcb-keysyms1-dev libpango1.0-dev \
                 libxcb-util0-dev libxcb-icccm4-dev libyajl-dev \
                 libstartup-notification0-dev libxcb-randr0-dev \
                 libev-dev libxcb-cursor-dev libxcb-xinerama0-dev \
                 libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev \
                 autoconf libxcb-xrm0 libxcb-xrm-dev automake \
                 libxcb-shape0-dev pkg-config meson

curl -LO https://i3wm.org/downloads/i3-4.24.tar.xz
tar -xzf i3-4.24.tar.xz
cd i3-4.24
mkdir build && cd build
meson ..

sudo ninja install

cd $dir

sudo apt install polybar

rm -rf /tmp/dev-env
