#!/usr/bin/env bash

sudo apt update
sudo apt install cmake g++ pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3

curl https://sh.rustup.rs -sSf | sh

source $HOME/.cargo/env

cargo install alacritty
