#!/usr/bin/env bash

sudo apt install libevent-dev ncurses-dev build-essential bison pkg-config

git clone https://github.com/tmux/tmux.git $HOME/code/tools/tmux
cd $HOME/code/tools/tmux
sh autogen.sh
./configure
make && sudo make install
