#!/usr/bin/env bash

mkdir /tmp/dev-env
cd /tmp/dev-env

curl -LO https://go.dev/dl/go1.24.0.linux-amd64.tar.gz

sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf go1.24.0.linux-amd64.tar.gz

# binary will be $(go env GOPATH)/bin/golangci-lint
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.5

golangci-lint --version
