#!/usr/bin/env bash

sudo apt -y update
sudo apt -y install curl git ripgrep pavucontrol xclip jq tldr shutter python3-pip playerctl

git clone https://github.com/junegunn/fzf $HOME/code/tools/fzf
$HOME/code/tools/fzf/install
